services:
  es01:
    image: elasticsearch:8.6.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=netology
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - node.roles=[data, remote_cluster_client, master, data_content, transform, data_hot, ml, ingest]
    ports:
      - 9200:9200

  es02:
    image: elasticsearch:8.6.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=netology
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - node.roles=[data_cold, remote_cluster_client, master, data_warm, data_content, transform, ml, data_frozen, ingest]
    depends_on:
      - es01

  kibana:
    image: kibana:8.6.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=["http://es01:9200"]
    ports:
      - 5601:5601
    depends_on:
      - es01
      - es02

  logstash:
    image: logstash:8.6.1
    container_name: logstash
    environment:
      - LANG=C.UTF-8
    volumes:
      - ./files/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./files/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - 12345:12345
    depends_on:
      - es01
      - es02

  filebeat:
    image: elastic/filebeat:8.6.1
    container_name: filebeat
    user: root
    environment:
      - LANG=C.UTF-8
    volumes:
      - ./files/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - logstash